<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\PharmaBridge.Abstraction\PharmaBridge.Abstraction.csproj" />
    <ProjectReference Include="..\..\Core\PharmaBridge.Domain\PharmaBridge.Domain.csproj" />
  </ItemGroup>

</Project>
