<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
  </ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\..\PharmaBridge.Shared\PharmaBridge.Shared.csproj" />
		<ProjectReference Include="..\PharmaBridge.Abstraction\PharmaBridge.Abstraction.csproj" />
		<ProjectReference Include="..\PharmaBridge.Domain\PharmaBridge.Domain.csproj" />
	</ItemGroup>

</Project>